steps:
  # Install LangGraph CLI and generate Dockerfile in the same step
  - name: 'python:3.12'
    entrypoint: 'sh'
    args: ['-c', 'pip install langgraph-cli && langgraph dockerfile -c langgraph.json Dockerfile']

  # Build Docker image with tag (-t) and specified platform
  # Created with documentation: https://cloud.google.com/build/docs/building/build-containers
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/langgraph-repo/land-shark-demo-app:latest', '.' ]

  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/langgraph-repo/land-shark-demo-app:latest']

  # Deploy Docker image to Cloud Run with VPC Connector, using the image from Artifact Registry. 
  # Created with documentation: https://cloud.google.com/run/docs/deploying
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'land-shark-demo-app',
            '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/langgraph-repo/land-shark-demo-app:latest',
            '--region', 'us-central1',
            '--platform', 'managed',
            '--port', '8000',
            '--allow-unauthenticated',
            '--timeout', '1800s',
            '--memory', '2Gi',
            '--cpu', '2',
            '--vpc-connector', 'land-shark-vpc-con'
           ]
    secretEnv: ['LANGSMITH_API_KEY', 'OPENAI_API_KEY']
substitutions:
  _PROJECT_ID: $PROJECT_ID
options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/agent-exec/secrets/LANGSMITH_API_KEY/versions/1
    env: LANGSMITH_API_KEY
  - versionName: projects/agent-exec/secrets/OPENAI_API_KEY/versions/1
    env: OPENAI_API_KEY
