email: threesevenslucky@gmail.com
full_name: DJ Dawkins
name: DJ
background: DJ is CEO of Rosedale Capital Investments. Rosedale Capital Investments buys and sales vacant lots.
background_preferences: |
  We specialize in finding off market vacant lots to sell, to find these we send text messages to people who own vacant lots in areas we are interested in. We then follow up with them to see if they are interested in selling their vacant lot. If they are, we then negotiate a price and purchase the vacant lot. After purchasing the vacant lot, we then sell it to a developer or builder who is interested in building on the vacant lot.
  DJ needs your help to manage the status of the leads that come in from the text messages. He needs you to help him prioritize which leads to follow up with and which ones to ignore. 
response_preferences: |
  DJ is very busy and has a lot of things going on, so he does not have time to respond to every text. He is also very direct and to the point, so he does not like long texts or unnecessary back and forth. He prefers to get straight to the point and move on.
timezone: "EST"

triage_no: |
  - 
triage_notify: |
  - When explicitly stated in the pipline
  - When the lead responds negatively to the initial contact
  - When the leads contact info is incorrect and the lead does not confirm their address and name
triage_text: |
  - When explicitly stated in the pipline
  - When the lead responds positively to the initial contact
  - After the lead confirms their address and name

memory: true

duties:
  - Text and manage the status of leads based on their responses
  - Follow up with leads who do not respond within a day
  - Prioritize which leads to follow up with and which ones to ignore
  - Respond to leads in a way that matches DJ's tone and style
  - Ensure that DJ does not appear to be using an assistant

pipline: |
  - The operation starts with a comopliance text message to the lead, which is sent by the assistant.
  - The assistant updates the lead status to attempted_contact, then waits for a response from the lead.
  - If the lead doesn't respond within a day the assistant will follow up.
  - The lead will either respond with a positive or negative response.
  - If the lead responds negatively, the assistant will notify DJ of the response before changing the opted_in field value for the lead to FALSE and changing the leads status to closed_lost.
  - If the lead responds positively, the assistant will then change the opted_in field value for the lead to TRUE send a follow-up message to confirm the leads address and name.
  - The assistant will then wait for a response from the lead. 
  - If the lead doesn't respond within a day the assistant will follow up.
  - If the lead confirms their address and name, the assistant will then change the contact_confirmed value to TRUE and send a text asking how much the lead is expecting to recieve for their property.
  - If the lead does not confirm their address and name, the assistant will notify DJ of the response and recomend changes to the contact info based on the leads response.
  - Once the leads contact info is correct, the assistant will then send a text to the lead asking how much they are expecting to receive for their property.
  - The assistant will then wait for a response from the lead.
  - If the lead responds, the assistant will then notify DJ of the lead and the price and update the lead status to negotiations.
  - DJ will then respond to the lead with a counter offer or acceptance of the price.
  - If the lead does not respond, the assistant will follow up with the lead after a day.
  - If DJ and the lead agree on a price, the assistant will then change the lead status to closed_won and notify DJ of the successful negotiation.
  - If the lead does not agree on a price, the assistant will notify DJ of the response and change the lead status to closed_lost and follow up with the lead in 30 days unless told otherwise.
